### ISSUE TITLE
Will it provide live scores?

### ISSUE THREAD

**Issue by guilhermecgs** [raminmr/free-api-worldcup2022#1]
hi!

great job! this is the only location I found such an API

My question:
Will it provide live scores? What is the expected delay?

**Comment by raminmr** [comment]
> Hello
> thank you
> The results will be updated after a 30-second delay

Hello
thank you
The results will be updated after a 30-second delay

**Comment by guilhermecgs** [comment]
Great news. I will be an user.


If there is a docker image for this api,  that would be a plus. It would avoid any major workload during the games
