### ISSUE TITLE
Croatia Vs Canada wrong score should be 4 to 1.

### ISSUE THREAD

**Issue by tux2208** [raminmr/free-api-worldcup2022#102]
![image](https://user-images.githubusercontent.com/111603396/204153282-59159adc-9ad2-4a03-8839-6107238de946.png)

**Comment by raminmr** [comment]
fixed

**Comment by tux2208** [comment]
Thanks, Gracias

**Comment by limebowler** [comment]
This doesn't appear to have been resolved in the Standings data. The overall Goals For/Against for both Croatia and Canada are incorrect.
