### ISSUE TITLE
Request failed with status code 402

### ISSUE THREAD

**Issue by HenglyEver** [raminmr/free-api-worldcup2022#106]
`402 HTTP` is Payment Required. I'm not sure if it is intended but I have set up a server that requests `/match` every minute and caches it so that the client website doesn't have to ping the API a lot and it also helps the auth flow. I read in another thread that the threshold is 1000 requests per 15mn per IP. My setup only sends 1 request per minute (15 req per 15mn) and I constantly get 402.

**Comment by rezarahiminia** [comment]
Hello, there was a problem with the gateway, now you shouldn't have any problems
