### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by tux2208** [raminmr/free-api-worldcup2022#107]
![image](https://user-images.githubusercontent.com/111603396/204394056-8461302f-49c7-49d8-9a56-65c3841a45ad.png)

please help us out!!

**Comment by wwebbs** [comment]
Too bad, experiencing the same here...

**Comment by timeuz** [comment]
504 - still timeout here

**Comment by MarcosRibeiroJesus** [comment]
Same here =/

**Comment by ftjn213** [comment]
same  504 error ...

**Comment by amirmahdioun** [comment]
same here 
504 gateway time out !
@raminmr

**Comment by ftjn213** [comment]
504 gateway time out !
@raminmr

**Comment by rezarahiminia** [comment]
fixed

**Comment by ftjn213** [comment]
it's still there ... 504 gateway time out !
@raminmr

**Comment by amirmahdioun** [comment]
I still have 504 error!
@raminmr

**Comment by MarcosRibeiroJesus** [comment]
Guys, you can try again, it worked for me just right now.
@amirmahdioun @ftjn213

**Comment by tux2208** [comment]
@raminmr thanks you so much.
