### ISSUE TITLE
504 Error  

### ISSUE THREAD

**Issue by ftjn213** [raminmr/free-api-worldcup2022#109]
data: '<html>\r\n' +
      '<head><title>504 Gateway Time-out</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
      '<hr><center>openresty</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'

**Comment by dmzoneill** [comment]
api is down, gateway error as @ftjn213 posted above

**Comment by rezarahiminia** [comment]
The problem was with the gateway. Solved

**Comment by ftjn213** [comment]
yes, it's resolved ,thanks @raminmr  !
