### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by dbarker1** [raminmr/free-api-worldcup2022#110]
Requesting any endpoint currently results in a 504 HTTP error.

`<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n`

**Comment by GirlWhoCode9** [comment]
yes check console this is the error : 
![image](https://user-images.githubusercontent.com/61971476/204517774-b65c7a54-2dbb-4086-b442-324a0defd564.png)

**Comment by sebapoe** [comment]
@raminmr Is the gateway problem an issue because of an overload of the server? Because it looks like it keeps coming back

**Comment by dbarker1** [comment]
Seems to have been fixed.
