### ISSUE TITLE
Netherlands v Qatar - wrong score

### ISSUE THREAD

**Issue by dbarker1** [raminmr/free-api-worldcup2022#112]
Netherlands scored, not Qatar. The score is NED 1 - 0 QAT.

**Comment by tux2208** [comment]
Same here!!

**Comment by dbarker1** [comment]
...now 2 - 0 to Netherlands--response says 0 - 2 to Qatar 🚀

**Comment by HenglyEver** [comment]
Same. I was actually surprised at first, like Qatar 2 and Netherlands 0??? Then I checked Google to confirm and it is not correct.

**Comment by rezarahiminia** [comment]
fixed
