### ISSUE TITLE
Unauthorized when using Axios

### ISSUE THREAD

**Issue by doxkhai** [raminmr/free-api-worldcup2022#114]
I made a simple request with **Axios**, setting headers with token and stuff but still get Unauthorized. However when im fetching the data with Curl it works well. Im using ExpressJS btw
Can someone please help me

<img width="764" alt="Screen Shot 2022-11-30 at 23 01 06" src="https://user-images.githubusercontent.com/90144623/204847305-c61a4bdf-7065-403c-bc63-c7367810cc96.png">
<img width="485" alt="Screen Shot 2022-11-30 at 23 01 34" src="https://user-images.githubusercontent.com/90144623/204847412-22f62b59-1204-47b1-b794-52e556f0ef46.png">

**Comment by 0xGetM** [comment]
![accesinfg API](https://user-images.githubusercontent.com/111920714/204850424-9d0f8851-ca74-4c1e-80d2-607f1daa7f23.png)
![login](https://user-images.githubusercontent.com/111920714/204850425-c6fcebcc-79cd-4e88-9f28-cdda46e02165.png)


I hope these screenshots can help, try to only send the authorization in the Header, no need to specify the content-type

it works fine for me
