### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by RodrigoAES** [raminmr/free-api-worldcup2022#119]
I try to access the all matches and receive the status 504 response:

<html>

<head>
	<title>504 Gateway Time-out</title>
</head>

<body>
	<center>
		<h1>504 Gateway Time-out</h1>
	</center>
	<hr>
	<center>openresty</center>
</body>

</html>

**Comment by johnnydevelops** [comment]
The server is down - from what i understand.

**Comment by djdmg** [comment]
I thinks too is down, i make only 2 request every 5min and is not working :-( 
Maybe some users overload the server by makink tons of requests every seconds
