### ISSUE TITLE
"status": "error",     "message": "Cannot read property 'name_fa' of undefined"

### ISSUE THREAD

**Issue by RodrigoAES** [raminmr/free-api-worldcup2022#120]
I received this Response:

"status": "error",
"message": "Cannot read property 'name_fa' of undefined"]

Can someone help me?

**Comment by johnnydevelops** [comment]
The server is down - from what i understand.

**Comment by dmzoneill** [comment]
gatway issue, your login failed

**Comment by raminmr** [comment]
fixed
