### ISSUE TITLE
status: 504,     statusText: 'Gateway Time-out

### ISSUE THREAD

**Issue by dmzoneill** [raminmr/free-api-worldcup2022#121]
[AxiosError: Request failed with status code 504] {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 62
    },
    method: 'post',
    url: 'http://api.cup2022.ir/api/v1/user/login',
    data: '{......................................................}'

response: {
    status: 504,
    statusText: 'Gateway Time-out',
    headers: {
      server: 'openresty/1.21.4.1',
      date: 'Thu, 01 Dec 2022 22:31:20 GMT',
      'content-type': 'text/html; charset=utf-8',
      'content-length': '164',
      connection: 'close',
      'x-apisix-upstream-status': '504'
    },

**Comment by johnnydevelops** [comment]
The server is down - from what i understand.

**Comment by ayan-de** [comment]
ALTERNATE-
https://world-cup.codsfli.com/points.php

**Comment by rezarahiminia** [comment]
fixed
