### ISSUE TITLE
Duplicate Match Id in /api/v1/match

### ISSUE THREAD

**Issue by klevisndoka** [raminmr/free-api-worldcup2022#124]
In api call '/api/v1/match' there are two matches with id 51

- "home_team_en": "Poland",
- "away_team_en": "France",

and
- "home_team_en": "Senegal",
- "away_team_en": "England",

Should we consider id as unique?

**Comment by Moritzjenny** [comment]
Yes please fix this

**Comment by rezarahiminia** [comment]
fixed id= 64
