### ISSUE TITLE
504 error

### ISSUE THREAD

**Issue by bumbeishvili** [raminmr/free-api-worldcup2022#129]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/6873202/205686150-f9e95dd5-6666-4c20-bbf6-41117d178617.png">

**Comment by rezarahiminia** [comment]
fixed

**Comment by bumbeishvili** [comment]
Now receiving 502

![image](https://user-images.githubusercontent.com/6873202/205862800-5ecb5cec-efb7-462e-8727-dcd3339050d1.png)
