### ISSUE TITLE
APi webserver is unreacheable

### ISSUE THREAD

**Issue by djdmg** [raminmr/free-api-worldcup2022#13]
APi webserver is actually unreacheable http://api.cup2022.ir

**Comment by Wett-Brito** [comment]
Same here

**Comment by Streemanu** [comment]
+1

**Comment by artupski** [comment]
yes, me too. trying to access but i can't, even with vpn.

**Comment by pr0m0schjn0** [comment]
Same here :(

**Comment by emocasares** [comment]
Hey. Same here. But now I'm getting 502 status code

**Comment by raminmr** [comment]
The problem was solved

**Comment by djdmg** [comment]
Thanks a lot 😀

Le sam. 22 oct. 2022, 07:23, reza rahiminia ***@***.***> a
écrit :
