### ISSUE TITLE
gateway down again

### ISSUE THREAD

**Issue by dmzoneill** [raminmr/free-api-worldcup2022#131]
},
    data: '<html>\r\n' +
      '<head><title>504 Gateway Time-out</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
      '<hr><center>openresty</center>\r\n' +
      '</body>\r\n' +
      '

**Comment by rezarahiminia** [comment]
fixed
