### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by DeFaXoR** [raminmr/free-api-worldcup2022#132]

**Comment by dcardonac31** [comment]
![image](https://user-images.githubusercontent.com/42297517/205775331-207b0f6a-0d23-4854-940c-fbf7beacb8b7.png)

**Comment by MohsinAhmedShaikh** [comment]
> ![image](https://user-images.githubusercontent.com/42297517/205775331-207b0f6a-0d23-4854-940c-fbf7beacb8b7.png)

Same

**Comment by rezarahiminia** [comment]
fixed
