### ISSUE TITLE
Wasn't able to get data for the last 14 hours

### ISSUE THREAD

**Issue by Moritzjenny** [raminmr/free-api-worldcup2022#133]
I can't login anymore since 14 hours, 504, 502 and 429

**Comment by wwebbs** [comment]
Same here...

**Comment by bumbeishvili** [comment]
Same, receiving this error when trying to login

![image](https://user-images.githubusercontent.com/6873202/205863142-965642ad-a497-404a-a3fa-f569a084325a.png)

**Comment by rezarahiminia** [comment]
fixed
