### ISSUE TITLE
Missing Goal in France vs. Australia

### ISSUE THREAD

**Issue by Harry-Knox-Instil** [raminmr/free-api-worldcup2022#138]
Match ID : 629c9c8a5749c4077500eadb 
The above match is a missing a second Giroud goal.

Thanks

**Comment by Harry-Knox-Instil** [comment]
Similarly, Casemiro's goal for Brazil, in Brazil vs. Switzerland, is missing.
Match ID : 629c9c8a5749c4077500eaf2

**Comment by rezarahiminia** [comment]
fixed
