### ISSUE TITLE
Matches by day match and single match endpoints are not working

### ISSUE THREAD

**Issue by juaning** [raminmr/free-api-worldcup2022#14]
As the title says, the matches by match day endpoint returns and empty array:
GET http://api.cup2022.ir/api/v1/bymatch/{id}

The single match endpoint throws an error (Bad Request)
GET http://api.cup2022.ir/api/v1/match/{id}
{"status":"error","message":"Cannot read property 'home_team_id' of undefined"}

Thanks for your hard work mate

**Comment by raminmr** [comment]
curl --location --request GET 'http://localhost:3040/api/v1/bymatch/3' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjliMjJlYTZiOGYwZTVlNGNkZDcxZDMiLCJpYXQiOjE2NjY1MDM1OTgsImV4cCI6MTY2NjU4OTk5OH0.ocQcHrrSUyzvHoVnFzNjpqlv9p68r4PPPyEr618jh9s' \
--header 'Content-Type: application/json' \
--data-raw '{
            "name_en": "South Korea",
            "name_fa": "کره جنوبی",
            "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png",
            "fifa_code": "KOR",
            "iso2": "KR",
            "groups": "H",
            "id": "32"
        }'

**Comment by raminmr** [comment]
`curl --location --request GET 'http://localhost:3040/api/v1/bymatch/1' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjliMjJlYTZiOGYwZTVlNGNkZDcxZDMiLCJpYXQiOjE2NjY1MDM1OTgsImV4cCI6MTY2NjU4OTk5OH0.ocQcHrrSUyzvHoVnFzNjpqlv9p68r4PPPyEr618jh9s' \
--header 'Content-Type: application/json'`

**Comment by raminmr** [comment]
`curl --location --request GET 'http://localhost:3040/api/v1/match/1' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjliMjJlYTZiOGYwZTVlNGNkZDcxZDMiLCJpYXQiOjE2NjY1MDM1OTgsImV4cCI6MTY2NjU4OTk5OH0.ocQcHrrSUyzvHoVnFzNjpqlv9p68r4PPPyEr618jh9s' \
--header 'Content-Type: application/json'`

It is based on the "id" of each match

**Comment by juaning** [comment]
Correct, the thing is that is failing:
![image](https://user-images.githubusercontent.com/1272442/198061477-3a65dffd-8700-4664-a241-305b5536e7f3.png)

And the one /bymatch is just returning empty for any given day
![image](https://user-images.githubusercontent.com/1272442/198061746-ce2eb1b6-df5a-436b-992a-a78469b26457.png)

**Comment by raminmr** [comment]
problem solved
