### ISSUE TITLE
Too many requests, please try again later.

### ISSUE THREAD

**Issue by phatdq101** [raminmr/free-api-worldcup2022#15]
I try to develop an app by using `http://api.cup2022.ir/api/v1/match` but often receive `Too many requests, please try again later.` error

**Comment by raminmr** [comment]
hi
How many requests per minute?

**Comment by phatdq101** [comment]
I requested the same one over 10 times and got the error

**Comment by raminmr** [comment]
Please send a curl request

**Comment by LalremLian** [comment]
"status": "error",
    "message": "User validation failed: password: Please provide your password, email: Please provide your email, name: Please provide your name"


I'm not able to create an account.

**Comment by djdmg** [comment]
> "status": "error", "message": "User validation failed: password: Please provide your password, email: Please provide your email, name: Please provide your name"
> 
> I'm not able to create an account.

Can we see your curl without the real password please ?

**Comment by LalremLian** [comment]
> Can we see your curl without the real password please ?

here's the crul:

curl --location --request POST 'http://api.cup2022.ir/api/v1/user' \
--form 'name="Doss"' \
--form 'email="blahblah@gmail.com"' \
--form 'password="12345678"' \
--form 'passwordConfirm="12345678"'

**Comment by djdmg** [comment]
> > Can we see your curl without the real password please ?
> 
> here's the crul:
> 
> curl --location --request POST 'http://api.cup2022.ir/api/v1/user' --form 'name="Doss"' --form 'email="[blahblah@gmail.com](mailto:blahblah@gmail.com)"' --form 'password="12345678"' --form 'passwordConfirm="12345678"'

You Curl is not correctly encoded i thinks. You should follow the example : curl --location --request POST 'http://api.cup2022.ir/api/v1/user' \
--header 'Content-Type: application/json' \
--data-raw '{
"name" : "Reza RAhiminia",
"email": "r.rahiminia@gmail.com",
"password": "******",
"passwordConfirm" : "******"
}'

Because actualy you not send the JSON to the server.

**Comment by LalremLian** [comment]
@djdmg 

![Screenshot_2](https://user-images.githubusercontent.com/68969199/198271022-6166793e-726d-4881-b7c9-1596ffab1740.png)


I was testing on Postman

**Comment by djdmg** [comment]
[](url)> @djdmg
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/68969199/198271022-6166793e-726d-4881-b7c9-1596ffab1740.png)
> 
> I was testing on Postman

You should use postman like this: 

![image](https://user-images.githubusercontent.com/13297768/198277495-1535e506-5e86-484a-9e61-822e65b6756d.png)

**Comment by LalremLian** [comment]
@djdmg 

It's just the same thing bro 😊

**Comment by djdmg** [comment]
@LalremLian 
![image](https://user-images.githubusercontent.com/13297768/198307474-11764651-a5fd-44e1-9841-dd2cb3da6dec.png) use like this and is work ;)

**Comment by raminmr** [comment]
> use like this and is work ;)



> @djdmg
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/68969199/198271022-6166793e-726d-4881-b7c9-1596ffab1740.png)
> 
> I was testing on Postman
![image](https://user-images.githubusercontent.com/12150722/198534787-59e123ab-64ec-474d-bddf-67c3decedf31.png)

You are using data form which is wrong
You must use raw

**Comment by LalremLian** [comment]
@djdmg @raminmr Here is an example. I did the same as you guys said to me to do so. Still, I'm facing the error.

![Screenshot_4](https://user-images.githubusercontent.com/68969199/198929260-9a6aec8e-3da1-4a2d-a83b-fd7893de8bb4.png)

**Comment by djdmg** [comment]
> @djdmg @raminmr Here is an example. I did the same as you guys said to me to do so. Still, I'm facing the error.
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/68969199/198929260-9a6aec8e-3da1-4a2d-a83b-fd7893de8bb4.png)

You have to choose JSON instead of text
