### ISSUE TITLE
"Cannot read property 'home_team_id' of undefined" on match by ID endpoint

### ISSUE THREAD

**Issue by DamianCabrio** [raminmr/free-api-worldcup2022#17]
Hello, like the title says, when I try to make a request to the match by ID endpoint, the error "Cannot read property 'home_team_id' of undefined" appears.

This is the request I'm making:
curl --location --request GET 'http://api.cup2022.ir/api/v1/match/1' \
--header 'Authorization: Bearer ******'

Thank you for this great API!

**Comment by raminmr** [comment]
> Hello, like the title says, when I try to make a request to the match by ID endpoint, the error "Cannot read property 'home_team_id' of undefined" appears.
> 
> This is the request I'm making: curl --location --request GET 'http://api.cup2022.ir/api/v1/match/1' --header 'Authorization: Bearer ******'
> 
> Thank you for this great API!

Thanks for the report
resolved
