### ISSUE TITLE
Error: Request timed out

### ISSUE THREAD

**Issue by ivangago06** [raminmr/free-api-worldcup2022#18]
Good evening, I try to consume any end point and it shows me Error: Request timed out, do you know if the service is down?

Cheers

**Comment by raminmr** [comment]
> Good evening, I try to consume any end point and it shows me Error: Request timed out, do you know if the service is down?
> 
> Cheers

Hello, no, the server is up, please send a request sample

**Comment by ivangago06** [comment]
Thank you very much for your prompt response, I can consume the API without any problem. On the other hand, I have a question... how long does the token expire? Is there a request limit?

Regards!
