### ISSUE TITLE
Typo in teams URL

### ISSUE THREAD

**Issue by mbenmclean** [raminmr/free-api-worldcup2022#2]
There is a typo in the teams URL. There are two `http://`
https://github.com/raminmr/free-api-worldcup2022#request-2

**Comment by raminmr** [comment]
> There is a typo in the teams URL. There are two `http://` https://github.com/raminmr/free-api-worldcup2022#request-2

Hello
Thanks for the report
Was corrected
If there is a problem, please let me know
