### ISSUE TITLE
Proper Ducumentation

### ISSUE THREAD

**Issue by lifeofdekisugi** [raminmr/free-api-worldcup2022#21]
Hey, I'm trying to make an android app with your API. Can you please explain the full forms of 
`	"mp": "0",
	"w": "0",
	"l": "0",
	"pts": "0",
	"gf": "0",
	"ga": "0",
	"gd": "0",`
	
It is in the Standings endpoint.

**Comment by raminmr** [comment]
"mp" =>  matches played
 "w"    =>  matches won
 "l"      =>  matches lost
 "pts"  =>  point / score
 "gf"   =>   goals for
 "ga"  =>   goals against
 "gd"  =>   goals difference
 "d"  =>     drawn
