### ISSUE TITLE
Player stats, stadiums etc. 

### ISSUE THREAD

**Issue by JochemZ** [raminmr/free-api-worldcup2022#22]
Is this project still a WIP? Are you going to add player information? So which player played in which match who are the TOP scorers etc?
Are you also going to add team formations? so which player played at which location in the team?

just some questions/ideas ;)

**Comment by raminmr** [comment]
> Is this project still a WIP? Are you going to add player information? So which player played in which match who are the TOP scorers etc? Are you also going to add team formations? so which player played at which location in the team?
> 
> just some questions/ideas ;)

It is a good suggestion
If I have a chance, I will definitely add it
There is no data for teams
