### ISSUE TITLE
 Wrong Groups

### ISSUE THREAD

**Issue by ivangago06** [raminmr/free-api-worldcup2022#23]
Hello, in group D Mexico and Poland are repeated.

the end point is: http://api.cup2022.ir/api/v1/standings

I thank you very much in advance, very good job you did.

I look forward to your comments.

**Comment by raminmr** [comment]
> 

thank you
I did not see such a problem
Try using this address:
/api/v1/standings/D

**Comment by raminmr** [comment]
> Hello, in group D Mexico and Poland are repeated.
> 
> the end point is: http://api.cup2022.ir/api/v1/standings
> 
> I thank you very much in advance, very good job you did.
> 
> I look forward to your comments.

thank you
I did not see such a problem
Try using this address:
/api/v1/standings/D

**Comment by ivangago06** [comment]
Thank you for your prompt response, also in that direction the same error comes out.

I look forward to your comments.

**Comment by raminmr** [comment]
Is it possible to explain more?
Or upload a photo

**Comment by ivangago06** [comment]
Of course...
End Point: http://api.cup2022.ir/api/v1/standings
Method: GET
group: C & group D México y Polnad are repeated.
apiResponse:

{
    "status": "success",
    "data": [
        {
            "_id": "629c9c7c5749c4077500eaca",
            "group": "A",
            "teams": [
                {
                    "team_id": "1",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "قطر",
                    "name_en": "Qatar",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/125px-Flag_of_Qatar.svg.png"
                },
                {
                    "team_id": "2",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "اکوادور",
                    "name_en": "Ecuador",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png"
                },
                {
                    "team_id": "3",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "سنگال",
                    "name_en": "Senegal",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png"
                },
                {
                    "team_id": "4",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "هلند",
                    "name_en": "Nederland",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png"
                }
            ]
        },
        {
            "_id": "629c9c7c5749c4077500eacb",
            "group": "B",
            "teams": [
                {
                    "team_id": "5",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "انگلستان",
                    "name_en": "England",
                    "flag": "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png"
                },
                {
                    "team_id": "6",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "ایران",
                    "name_en": "Iran",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg"
                },
                {
                    "team_id": "7",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "آمریکا",
                    "name_en": "United States",
                    "flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png"
                },
                {
                    "team_id": "8",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "ولز",
                    "name_en": "Wales",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Wales_%281959%29.svg/125px-Flag_of_Wales_%281959%29.svg.png"
                }
            ]
        },
        {
            "_id": "629c9c7c5749c4077500eacc",
            "group": "C",
            "teams": [
                {
                    "team_id": "9",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "آرژانتین",
                    "name_en": "Argentina",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png"
                },
                {
                    "team_id": "10",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "عربستان",
                    "name_en": "Saudi Arabia",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png"
                },
                {
                    "team_id": "13",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "مکزیک",
                    "name_en": "Mexico",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png"
                },
                {
                    "team_id": "14",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "لهستان",
                    "name_en": "Poland",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png"
                }
            ]
        },
        {
            "_id": "629c9c7c5749c4077500eacd",
            "group": "D",
            "teams": [
                {
                    "team_id": "13",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "مکزیک",
                    "name_en": "Mexico",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png"
                },
                {
                    "team_id": "14",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "لهستان",
                    "name_en": "Poland",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png"
                },
                {
                    "team_id": "11",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "دانمارک",
                    "name_en": "Denmark",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png"
                },
                {
                    "team_id": "12",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "تونس",
                    "name_en": "Tunisia",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png"
                }
            ]
        },
        {
            "_id": "629c9c7c5749c4077500eace",
            "group": "E",
            "teams": [
                {
                    "team_id": "21",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "اسپانیا",
                    "name_en": "Spain",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png"
                },
                {
                    "team_id": "22",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "کاستاریکا",
                    "name_en": "Costa Rica",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/125px-Flag_of_Costa_Rica_%28state%29.svg.png"
                },
                {
                    "team_id": "19",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "آلمان",
                    "name_en": "Germany",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png"
                },
                {
                    "team_id": "20",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "ژاپن",
                    "name_en": "Japan",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png"
                }
            ]
        },
        {
            "_id": "629c9c7c5749c4077500eacf",
            "group": "F",
            "teams": [
                {
                    "team_id": "17",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "مراکش",
                    "name_en": "Morocco",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png"
                },
                {
                    "team_id": "18",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "کرواسی",
                    "name_en": "Croatia",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png"
                },
                {
                    "team_id": "23",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "بلژیک",
                    "name_en": "Belgium",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png"
                },
                {
                    "team_id": "24",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "کانادا",
                    "name_en": "Canada",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png"
                }
            ]
        },
        {
            "_id": "629c9c7c5749c4077500ead0",
            "group": "G",
            "teams": [
                {
                    "team_id": "25",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "برزیل",
                    "name_en": "Brazil",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png"
                },
                {
                    "team_id": "26",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "صربستان",
                    "name_en": "Serbia",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/125px-Flag_of_Serbia.svg.png"
                },
                {
                    "team_id": "31",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "سوئیس",
                    "name_en": "Switzerland",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/100px-Flag_of_Switzerland.svg.png"
                },
                {
                    "team_id": "32",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "کامرون",
                    "name_en": "Cameroon",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/125px-Flag_of_Cameroon.svg.png"
                }
            ]
        },
        {
            "_id": "629c9c7c5749c4077500ead1",
            "group": "H",
            "teams": [
                {
                    "team_id": "29",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "اروگوئه",
                    "name_en": "Uruguay",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/125px-Flag_of_Uruguay.svg.png"
                },
                {
                    "team_id": "30",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "کره جنوبی",
                    "name_en": "South Korea",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png"
                },
                {
                    "team_id": "27",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "پرتغال",
                    "name_en": "Portugal",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png"
                },
                {
                    "team_id": "28",
                    "mp": "0",
                    "w": "0",
                    "l": "0",
                    "pts": "0",
                    "gf": "0",
                    "ga": "0",
                    "gd": "0",
                    "d": "0",
                    "name_fa": "غنا",
                    "name_en": "Ghana",
                    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/125px-Flag_of_Ghana.svg.png"
                }
            ]
        }
    ]
}

**Comment by raminmr** [comment]
Was corrected
Is it possible to know the address of your site?

**Comment by ivangago06** [comment]
I have my site locally, it has already been corrected, thank you very much, good job with this API

**Comment by ivangago06** [comment]
.
