### ISSUE TITLE
Can we get a schedule endpoint? 

### ISSUE THREAD

**Issue by CyrilNb** [raminmr/free-api-worldcup2022#24]
Hi, thanks for this API.
I would like to display a calendar, day by day of all the fixtures of the day.

Can we get a general schedule endpoint (chronological sorted?)

thanks!

**Comment by raminmr** [comment]
I added it for you

curl --location --request POST 'api.cup2022.ir/api/v1/bydate' \
--header 'Authorization: Bearer <token> \
--header 'Content-Type: application/json' \
--data-raw '{
    "date":"12/2/2022"
}'
