### ISSUE TITLE
wrong dates

### ISSUE THREAD

**Issue by ivangago06** [raminmr/free-api-worldcup2022#25]
Hello again friend, I discovered another information error, some matches the dates are wrong, I share an example, I really appreciate your help and I congratulate you for your great work with this API.

For this example, the match is 11/26 and not 11/23

Greetings.

![image](https://user-images.githubusercontent.com/66133327/198895633-b5d5d334-c6e7-40c8-ac00-a107c6e63f35.png)

**Comment by raminmr** [comment]
resolved
Thanks for the report
