### ISSUE TITLE
Time elapsed values

### ISSUE THREAD

**Issue by juaning** [raminmr/free-api-worldcup2022#27]
Hey mate, thanks for the hard work and quick responses.

What are the expected values for time_elapsed on matches endpoints?

`time_elapsed: "notstarted"`

During the game I guess is going to be minutes:seconds? what about once the match ends?
`time_elapsed: "finished"` perhaps?

Thanks again!

**Comment by raminmr** [comment]
Yes, exactly    time_elapsed: "finished"  

notstarted   |   h1  |   hf   |  h2  |  finished

If you developed an application. Please send the website or application address

**Comment by keny5551** [comment]
time_elapsed not works, 34 min and it is "started" not "h1"
