### ISSUE TITLE
What is the rate limit? Also, how you still offer it for free?

### ISSUE THREAD

**Issue by CyrilNb** [raminmr/free-api-worldcup2022#28]
Hi, amazing job.

I wanted to know what's the rate limit?
Also, how do you keep it free? If that scales, would you be able to keep it free?

Regards

**Comment by raminmr** [comment]
Thanks
Currently there is no limit
The use of this service is completely free.
If you developed an application. Please send the website or application address

**Comment by CyrilNb** [comment]
No limit? How can I be assure that if my app is used by thousands, your server will handle the load?

**Comment by raminmr** [comment]
Yes, there is no limit, for now, you cache the data on your side so that users don't call my server directly
If the number of requests increases, I will definitely limit it
