### ISSUE TITLE
Will it provide data for matches after the group stage?

### ISSUE THREAD

**Issue by guilhermecgs** [raminmr/free-api-worldcup2022#3]
hi @raminmr !

Just to be sure, will the API provide data for matches after the group stage?

**Comment by raminmr** [comment]
> hi @raminmr !
> 
> Just to be sure, will the API provide data for matches after the group stage?After the teams are determined in the stages (round of 16, quarter finals, semi finals, 3rd place and final), games are added to the tournament table.
