### ISSUE TITLE
Netherlands misspelled

### ISSUE THREAD

**Issue by gitgurra** [raminmr/free-api-worldcup2022#31]
Not a big issue but 'Nederland' is spelled 'Netherlands'

**Comment by raminmr** [comment]
fixed

**Comment by kavish-agarwal** [comment]
@raminmr I am not getting the correct spell 'th' should be there instead of 'd'.
Wrong:- 'Nederlands'
Correct:- 'Netherlands' 
Please find below the API response.
        {
            "_id": "629c9c8a5749c4077500eae6",
            "away_score": 0,
            "away_scorers": [
                "null"
            ],
            "away_team_id": "2",
            "finished": "FALSE",
            "group": "A",
            "home_score": 0,
            "home_scorers": [
                "null"
            ],
            "home_team_id": "4",
            "id": "19",
            "local_date": "11/25/2022 19:00",
            "matchday": "6",
            "persian_date": "1400-09-04 19:30",
            "stadium_id": "1",
            "time_elapsed": "notstarted",
            "type": "group",
            "home_team_fa": "هلند",
            "away_team_fa": "اکوادور",
            "home_team_en": **"Nederlands",**
            "away_team_en": "Ecuador",
            "home_flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png",
            "away_flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png"
        },
