### ISSUE TITLE
wrong schedule

### ISSUE THREAD

**Issue by jhontech32** [raminmr/free-api-worldcup2022#38]
I found some wrong schedule and it should be ...

* United States VS Wales ( 22/11/2022 )
* France VS Australia ( 23/11/2022 )
* Belgium VS Canada ( 24/11/2022 )
* Brazil VS Serbia ( 25/11/2022 )
* England VS United State ( 26/11/2022 )
* Argentina VS Mexico ( 27/11/2022 )
* Spain VS Germany ( 28/11/2022 )
* Portugal VS Uruguay ( 29/11/2022 )
* Iran VS United State ( 30/11/2022 )

and there are some more, please check again sir ..
Thank you :)

**Comment by ondapc** [comment]
Please make sure that you are using the official FIFA pdf
https://digitalhub.fifa.com/m/464f16f856f5ed05/original/FIFA-World-Cup-Qatar-2022-Match-Schedule.pdf

**Comment by ondapc** [comment]
I would setup the service for all 64 matches... the first 48 were set -- you should create 15 more slots ... even if they dont have names ( match outcomes ) but their "_id" are set, so when updated it will all be a single table. Programming this is not hard once match outcomes are input -- the hardest part of this service is a detail update of matches, scores, penalty outcomes ... times - hence your service.

1-48 =  Group ( ADD GRP )
49-56 = Round of 16 ( ADD R16 ) 
56-60 = Quarter ( ADD QR )
61-62 = 3rd Place / ADD 3RD )
63-64 = Final ( FIN )

adding one column to the table will complete this task ... from there you can add 5 more subsequent services 

http://api.cup2022.ir/api/v1/matches
http://api.cup2022.ir/api/v1/round16
http://api.cup2022.ir/api/v1/quarter
http://api.cup2022.ir/api/v1/semi
http://api.cup2022.ir/api/v1/fin  

Your service could be combined -- adding a few json segments to seperate the stages... 

Good luck!

**Comment by raminmr** [comment]
@jhontech32 
@ondapc 

fixed
