### ISSUE TITLE
How will the data from the round of 16, quarter, semifinals, final & 3rd place be handled?

### ISSUE THREAD

**Issue by ondapc** [raminmr/free-api-worldcup2022#41]
Interested in knowing if those match feeds will be updated automatically and if so -- what to expect?

**Comment by ondapc** [comment]
I would setup the service for all 64 matches... the first 48 were set -- you should create 15 more slots ... even if they dont have names ( match outcomes ) but their "_id" are set, so when updated it will all be a single table. Programming this is not hard once match outcomes are input -- the hardest part of this service is a detail update of matches, scores, penalty outcomes ... times - hence your service.

1-48 =  Group ( ADD GRP )
49-56 = Round of 16 ( ADD R16 ) 
56-60 = Quarter ( ADD QR )
61-62 = 3rd Place / ADD 3RD )
63-64 = Final ( FIN )

adding one column to the table will complete this task ... from there you can add 5 more subsequent services 

http://api.cup2022.ir/api/v1/matches
http://api.cup2022.ir/api/v1/round16
http://api.cup2022.ir/api/v1/quarter
http://api.cup2022.ir/api/v1/semi
http://api.cup2022.ir/api/v1/fin  

Your service could be combined -- adding a few json segments to seperate the stages... 

Which would look like the following:

http://api.cup2022.ir/api/v1/worldcup2022
>> matches = everything ( 64 matches )
>> round16
>> quarter
>> semi
>> fin

Good luck!

**Comment by raminmr** [comment]
> Interested in knowing if those match feeds will be updated automatically and if so -- what to expect?

Yes, it will be updated every 3 minutes

**Comment by raminmr** [comment]
> I would setup the service for all 64 matches... the first 48 were set -- you would need to create 15 more slots ... even if they dont have match outcomes, when updated it will all be a single table. The hardest part of this service is to detail updates, matches, scores, penalty outcomes ... hence your service.
> 
> 1-48 = Group ( ADD GRP ) 49-56 = Round of 16 ( ADD R16 ) 56-60 = Quarter ( ADD QR ) 61-62 = 3rd Place / ADD 3RD ) 63-64 = Final ( FIN )
> 
> adding one column to the table will complete this task ... from there you can add 5 more subsequent services
> 
> http://api.cup2022.ir/api/v1/matches http://api.cup2022.ir/api/v1/round16 http://api.cup2022.ir/api/v1/quarter http://api.cup2022.ir/api/v1/semi http://api.cup2022.ir/api/v1/fin
> 
> Your service could be combined -- adding a few json segments to seperate the stages...
> 
> Which would look like the following:
> 
> http://api.cup2022.ir/api/v1/worldcup2022
> 
> > > matches = everything ( 64 matches )
> > > round16
> > > quarter
> > > semi
> > > fin
> 
> Good luck!

Help if you like.
Please make the competition data based on the following data and send it to me.
I update the list of games


{
  "_id": {
    "$oid": "629c9c8a5749c4077500ead4"
  },
  "away_score": "0",
  "away_scorers": "null",
  "away_team_id": "4",
  "finished": "FALSE",
  "group": "A",
  "home_score": "0",
  "home_scorers": "null",
  "home_team_id": "3",
  "id": "1",
  "local_date": "11/21/2022 19:00",
  "matchday": "2",
  "persian_date": "1400-08-30 19:30",
  "stadium_id": "1",
  "time_elapsed": "notstarted",
  "type": "group"    | R16  |  QR  |  3RD  |  FIN
}
