### ISSUE TITLE
Too many requests, pleace try again later.

### ISSUE THREAD

**Issue by Moritzjenny** [raminmr/free-api-worldcup2022#48]
Is this your limitation to requests per user or do you have to many total requests incoming?
Will you fix this?

**Comment by raminmr** [comment]
> Will you fix this?

5 request per/min

**Comment by sp1z** [comment]
Just to add, I've left making any calls for a good 15 mins now and I'm still getting the message.  Is it 5 request per min per person, or 5 requests per min for all users?

**Comment by Moritzjenny** [comment]
I think you should make a new account and don‘t violate the limit, otherwise you will get the message for the rest of your lifetime

**Comment by sp1z** [comment]
Thanks.  It's difficult not to violate the limit when developing and testing data coming in, but I'll give it a try with another account.

**Comment by raminmr** [comment]
> If bandwidth is a problem, I'm happy to help with hosting - msg me.

I will upgrade the server during the tournament.
There is a number of requests per user

**Comment by mamitry** [comment]
I just tried to register and my first request was responded with "Too many requests, please try again later".  
Any chance this can be remediated before the tournament starts?

**Comment by mamitry** [comment]
I just tried to register and my first request was responded with "Too many requests, please try again later".  
Any chance this can be remediated before the tournament starts?

**Comment by raminmr** [comment]
> I just tried to register and my first request was responded with "Too many requests, please try again later". Any chance this can be remediated before the tournament starts?

Registration is not a problem now. 214 people registered today
If you get an error, try again

**Comment by mamitry** [comment]
> > I just tried to register and my first request was responded with "Too many requests, please try again later". Any chance this can be remediated before the tournament starts?
> 
> Registration is not a problem now. 214 people registered today If you get an error, try again

Yes, after giving it some more tries it did work. 

Thank You @raminmr for this cool API

**Comment by alex-p-chan** [comment]
I did not make 5 requests in 1 min and it still says `Too many requests, please try again later.`

**Comment by alex-p-chan** [comment]
If you are having server scaling issues I suggest you redesign to just have a static JSON which you modify via CRON job like this 
https://github.com/lsv/fifa-worldcup-2018

**Comment by raminmr** [comment]
> If you are having server scaling issues I suggest you redesign to just have a static JSON which you modify via CRON job or subscription like this https://github.com/lsv/fifa-worldcup-2018 edit found a 2022 version : https://github.com/estiens/world_cup_json

Because the result of the game is announced live during the game and the number of requests is very high. I am trying to fix it in the next few days.
Our server has one gig of RAM
:(

**Comment by raminmr** [comment]
If funding is provided for the server.
I will solve the cross-origin problem.

**Comment by 580** [comment]
> I did not make 5 requests in 1 min and it still says `Too many requests, please try again later.`

Same Issue Here.

**Comment by raminmr** [comment]
fixed 
// limit each IP to 1000 requests per 15 min

**Comment by raminmr** [comment]
> fixed
> // limit each IP to 1000 requests per 15 min

fixed
// limit each IP to 1000 requests per 15 min

**Comment by raminmr** [comment]
> Just to add, I've left making any calls for a good 15 mins now and I'm still getting the message. Is it 5 request per min per person, or 5 requests per min for all users?
> 
> EDIT: If bandwidth is a problem, I'm happy to help with hosting - msg me.

fixed
// limit each IP to 1000 requests per 15 min

**Comment by Moritzjenny** [comment]
Thanks, you are amazing!

**Comment by ViniBGoulart** [comment]
same issue, too many requests. The api is open source?

**Comment by masedri** [comment]
what is differences between https://github.com/estiens/world_cup_json and this project? @raminmr 

thanks for your amazing job!

**Comment by raminmr** [comment]
I don't know.
The results of our matches are live @masedri

**Comment by masedri** [comment]
thanks men @raminmr 

Just one question, the api response me Too many requests, please try again later. 

any solutition?

cheers.

**Comment by raminmr** [comment]
> thanks men @raminmr
> 
> Just one question, the api response me Too many requests, please try again later.
> 
> any solutition?
> 
> cheers.

The number of requests is limited because it is free
Maximum request 1000 in 15 minutes

**Comment by arwinsf** [comment]
Just wanted to say that for the free price the amount of requests granted per 15 minutes is really generous. Thank you a lot from Germany.
PS I'm Iranian as well

**Comment by tux2208** [comment]
I just make 1 per day I'm getting the result too many request today.

**Comment by Moritzjenny** [comment]
> I just make 1 per day I'm getting the result too many request today.

I guess if you made the request right around the start of the game, the system was briefly overloaded.. 3 minutes later it was fine again

**Comment by tux2208** [comment]
sorry i just renew trhe token, and works thanks
