### ISSUE TITLE
Match Type

### ISSUE THREAD

**Issue by juaning** [raminmr/free-api-worldcup2022#49]
Hey mate, once again thanks for your hard work, wondering what the options are for match type:

We get for group stage:
`"type": "group",`

any idea about next stages values yet?

**Comment by raminmr** [comment]
> 

"type": "group" | R16 | QR | 3RD | FIN

**Comment by raminmr** [comment]
> Hey mate, once again thanks for your hard work, wondering what the options are for match type:
> 
> We get for group stage: `"type": "group",`
> 
> any idea about next stages values yet?

"type": "group" | R16 | QR | 3RD | FIN

**Comment by juaning** [comment]
Sweet! thanks! I think is missing semifinals (SF)?

**Comment by raminmr** [comment]
> 3RD

3RD 

> 

3RD

**Comment by raminmr** [comment]
> Sweet! thanks! I think is missing semifinals (SF)?

3RD

**Comment by juaning** [comment]
What about the 3rd position match?
