### ISSUE TITLE
504 - Gateway Timeout

### ISSUE THREAD

**Issue by makeit-code** [raminmr/free-api-worldcup2022#51]
![image](https://user-images.githubusercontent.com/60301111/201936211-16a4e9c7-3dd9-4173-907d-248c19c81529.png)

Thanks for your free api. I used in my app to bet on matches with my friends, but unfortunately I ran into a problem after some time. I wanted to do standings download automation, but now I have connection error. 

Is there a lifetime of the tokken or can it be used once downloaded all the time?

**Comment by soclemys** [comment]
Hi,

I am currently also developing an app using this API. It seems the server is down at the moment. Perhaps we should wait a bit. I suspect the server would return a 401 (unauthorized) response if the issue is to do with the token itself.

**Comment by raminmr** [comment]
> Is there a lifetime of the tokken or can it be used once downloaded all the time?

**Comment by raminmr** [comment]
> > Is there a lifetime of the tokken or can it be used once downloaded all the time?

The system must have deleted your token to detect fraud
Login again
