### ISSUE TITLE
Wrong group information

### ISSUE THREAD

**Issue by guilhermecgs** [raminmr/free-api-worldcup2022#6]
I think the match api is with wrong data.

Brazil, for example, appears in two different groups

<img width="321" alt="image" src="https://user-images.githubusercontent.com/8465337/192936439-edd69bef-c941-4044-a5e4-66b89cff98b0.png">

**Comment by Atalaa** [comment]
Switzerland as well.

**Comment by raminmr** [comment]
> Switzerland as well.

Thank you for reporting
The problem is solved

**Comment by guilhermecgs** [comment]
Some other stuff:

- Iran flag is wrong: should be https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg
- Missing timezone information on the local_date
- "time_elapsed": "Final",  "finished": "true", even if the game hasn't started

**Comment by raminmr** [comment]
> The problem is solved

The problem is solved
