### ISSUE TITLE
Error Message: "Failed host lookup: 'api.cup2022.ir'"

### ISSUE THREAD

**Issue by bakteribaik** [raminmr/free-api-worldcup2022#62]
(Os error: No address associated with hostname)

![image](https://user-images.githubusercontent.com/64103383/202888831-e2819e35-d2c7-4229-b70e-a6d7d10edec0.png)

**Comment by ymerdrengene** [comment]
same here

**Comment by daffy-dev** [comment]
Same here

**Comment by AntinotyY** [comment]
same here

**Comment by avivbarniv** [comment]
Same

**Comment by LloydNicholson** [comment]
Same

**Comment by raminmr** [comment]
curl --location --request POST 'api.cup2022.ir/api/v1/user/login' \
--header 'Content-Type: application/json' \
--data-raw '{

"email": "",
"password": ""
 
}'


first Register

**Comment by mrchoke** [comment]
I found this case is the DNS issue.
if fix ip in /etc/hosts it still work.

**Comment by mrchoke** [comment]
some DNS server can reply.

![Screenshot 2022-11-21 at 00 10 34](https://user-images.githubusercontent.com/3403645/202915789-da5dff26-a9c9-4232-b6b2-5b925c8ca318.jpg)

**Comment by bakteribaik** [comment]
> curl --location --request POST 'api.cup2022.ir/api/v1/user/login' --header 'Content-Type: application/json' --data-raw '{
> 
> "email": "", "password": ""
> 
> }'
> 
> first Register

i have already registered before

**Comment by bakteribaik** [comment]
> I found this case is the DNS issue. if fix ip in /etc/hosts it still work.

so i need to setup my dns? I have tried this but still can't access the api url. i am trying to access api url with proxysite, but getting error 404 Not Found. previously the url was accessible, but not anymore.

![image](https://user-images.githubusercontent.com/64103383/202916336-81d248ec-89f8-45f0-a49a-5a6e873a4c0c.png)

**Comment by chuteuk** [comment]
It's down it seems. Probably not the best timing haha

**Comment by bakteribaik** [comment]
> I found this case is the DNS issue. if fix ip in /etc/hosts it still work.

ok, so I've tried setting up static dns like 1.1.1.1, 8.8.8.8 and others but it keeps me from reaching the API from those urls. so i changed my dns to default following the dns of the internet provider i used and it worked for a while after that the api url was unreachable again.

even though before I made this post, all things could be accessed properly.

**Comment by mrchoke** [comment]
> ok, so I've tried setting up static dns like 1.1.1.1, 8.8.8.8 and others but it keeps me from reaching the API from those urls. so i changed my dns to default following the dns of the internet provider i used and it worked for a while after that the api url was unreachable again.
> 

I fixed ip in /etc/hosts

**Comment by diegortx** [comment]
In Brazil the api offline any other place pffline too?

**Comment by raminmr** [comment]
This problem has arisen due to the European sanctions against Iran (Arvancloud). The problem will be solved in the next 2 hours

**Comment by bakteribaik** [comment]
> This problem has arisen due to the European sanctions against Iran (Arvancloud). The problem will be solved in the next 2 hours

Thanks for the information, glad to hear that 😁

**Comment by diegortx** [comment]
> This problem has arisen due to the European sanctions against Iran (Arvancloud). The problem will be solved in the next 2 hours

Great i'm wait for =)

**Comment by AntinotyY** [comment]
> This problem has arisen due to the European sanctions against Iran (Arvancloud). The problem will be solved in the next 2 hours

great news

**Comment by diegortx** [comment]
Here return !!! :+1:

**Comment by Moritzjenny** [comment]
I solved this on linux like this:

in /etc/resolv.conf set the value of nameserver to 1.1.1.1
-> This will use cloudflare as nameserver and it solved the problem for me.
