### ISSUE TITLE
bad statistics

### ISSUE THREAD

**Issue by ivangago06** [raminmr/free-api-worldcup2022#64]
I hope you are well, in your final standings point the winning team and its statistics are wrong, it must be Ecuador and not Senegal.

![image](https://user-images.githubusercontent.com/66133327/202918186-572aa6ed-1eb4-410d-b449-5b2a03bf619f.png)

**Comment by raminmr** [comment]
fixed
Can you send me the website address?

**Comment by ivangago06** [comment]
Of course: mundial.c3ntro.ocm on the other hand I found another error, in games won "w" must be 1 not 3.

I really appreciate your help.

![image](https://user-images.githubusercontent.com/66133327/202918484-1b85f866-ef0b-4550-80a3-5f3e5b7e8ae6.png)

**Comment by raminmr** [comment]
fixed
The first game was bugged :)

**Comment by ivangago06** [comment]
Thanks for your help, looks correct.

Excellent job
