### ISSUE TITLE
Error 429 every 15 minutes 

### ISSUE THREAD

**Issue by fouber** [raminmr/free-api-worldcup2022#72]
This api will very regularly report error 429 every 15 minutes (Too many requests, please try again later.) I have tried using different IPs, accounts and all get this error, I believe it is a global problem. I am very hopeful that this issue will be fixed.

Thanks again to the author of this project for his great contribution, and in a materialistic society, I admire the open source spirit!

**Comment by raminmr** [comment]
fixed
