### ISSUE TITLE
Cannot access from axios  in react js 

### ISSUE THREAD

**Issue by chhengsombathoudom** [raminmr/free-api-worldcup2022#74]
Access to XMLHttpRequest at 'http://api.cup2022.ir/api/v1/user/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by chhengsombathoudom** [comment]
Here is my code: 
   const uri = "http://api.cup2022.ir/api/v1/standings";
    const options = {
        headers: {
            'Authorization' : 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzdjNDNmYzQ4NzA5MjMzZmQ4NGMzOTEiLCJpYXQiOjE2NjkxMDM0MDAsImV4cCI6MTY2OTE4OTgwMH0.7rrp0ndZUB6BDzyt_KmkA4cKLrC6xvikJtKP6MJqLVA',
            'Content-Type' : 'application/json',
        },
    };
    
    const {data} = await axios.get(uri,options);
    console.log(data);
    return data;
}

**Comment by raminmr** [comment]
Do not call directly. Play through server or SSR
