### ISSUE TITLE
No data returned

### ISSUE THREAD

**Issue by JMGarc** [raminmr/free-api-worldcup2022#77]
Hi,
These endpoints are not returning results:
- http://api.cup2022.ir/api/v1/team/{Id}
- http://api.cup2022.ir/api/v1/bydate 

Response received:
(...)
Server: openresty/1.21.4.1
{
  "status": "success",
  "data": []
}

**Comment by raminmr** [comment]
curl --location --request POST 'api.cup2022.ir/api/v1/bydate' \
--header 'Authorization: Bearer {token}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "date":"12/2/2022"
}'

**Comment by JMGarc** [comment]
That is the request I'm using for the "bydate" and the described for "team id", but the response I've posted is what is being returned. 
All other endpoints are working as expected.

Note that I could not test again as the server seems to be down: "Internal Server Error. Unable to connect to the remote server"
