### ISSUE TITLE
match not ending 

### ISSUE THREAD

**Issue by amerhamdan3** [raminmr/free-api-worldcup2022#78]
"_id" => "629c9c8a5749c4077500ead9"
        "away_score" => 0
        "away_scorers" => array:1 [▶]
        "away_team_id" => "12"
        "finished" => "FALSE"
        "group" => "D"
        "home_score" => 0
        "home_scorers" => array:1 [▶]
        "home_team_id" => "11"
        "id" => "6"
        "local_date" => "11/22/2022 16:00"
        "matchday" => "3"
        "persian_date" => "1400-09-01 16:30"
        "stadium_id" => "1"
        "time_elapsed" => "finished"
        "type" => "group"
        "home_team_fa" => "دانمارک"
        "away_team_fa" => "تونس"
        "home_team_en" => "Denmark"
        "away_team_en" => "Tunisia"
        "home_flag" => "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png"
        "away_flag" => "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png"
        
        
        this match should be "finished" => "TRUE"

**Comment by chuteuk** [comment]
Yes this is currently causing an issue for me too.

**Comment by tux2208** [comment]
if v.Finished == "TRUE" || v.TimeElapsed == "finished" 

i add this to workaround the issue

**Comment by mrchoke** [comment]
Confirm !!
![Screenshot 2022-11-23 at 01 12 28](https://user-images.githubusercontent.com/3403645/203390499-15856233-b8c1-4390-8acf-4d0375f66b76.jpg)

**Comment by raminmr** [comment]
fixed

**Comment by raminmr** [comment]
Can you tell me the name of the site or application?

**Comment by mrchoke** [comment]
> Can you tell me the name of the site or application?

I use on local website for my group friends ^_^ 

Thank you for the  great api.
❤️

**Comment by raminmr** [comment]
> HI thanks for the API have been fun, still the problem with the status.
> 
> ![image](https://user-images.githubusercontent.com/111603396/203542294-aabdb691-6ade-4b3c-af3c-9769a1bfce5d.png)

fixed
