### ISSUE TITLE
Saudi Scorers Missing

### ISSUE THREAD

**Issue by PFound** [raminmr/free-api-worldcup2022#80]
![image](https://user-images.githubusercontent.com/11212973/203503894-05448765-8573-4764-925a-efb09babf457.png)

Missing the scorers for Saudi Arabia. Should include: 

Saleh Al Shehri, Salem Al Dawsari

**Comment by PFound** [comment]
France and Australia scorers are also missing.

**Comment by raminmr** [comment]
fixed
