### ISSUE TITLE
Live matches taking too long to update

### ISSUE THREAD

**Issue by Brian-Weloba** [raminmr/free-api-worldcup2022#82]
the Germany game is 1-0 at half time but the api is still at 0-0 and has not updated the time

**Comment by HenglyEver** [comment]
I am having the same problems.

**Comment by Moritzjenny** [comment]
Same

**Comment by jkleroy** [comment]
Same here

**Comment by DrCuddless** [comment]
I'm under the impression that the guy who runs this api just updates the data himself so it's when he can get to updating it really. I've noticed some of the scorers are missing also.

**Comment by fr4nkln11** [comment]
Is web scraping a good alternative for getting data like scorers names or line-ups?

**Comment by jkleroy** [comment]
Although this API is quite good for small (free) projects, I decided to move on to https://live-score-api.com which is much more reliable and has more data.
