### ISSUE TITLE
Incorrect name of the scorer Switzerland vs Cameroon

### ISSUE THREAD

**Issue by dcardonac31** [raminmr/free-api-worldcup2022#94]
![image](https://user-images.githubusercontent.com/42297517/203882160-ca150204-cea8-413a-b000-3defff0484c1.png)

![image](https://user-images.githubusercontent.com/42297517/203882038-6ac9f463-2373-41c1-b7ef-7183e7a48b27.png)

**Comment by raminmr** [comment]
fixed
